version: 2

models:
  - name: stg_green_tripdata
    description: >
      Staging model for green taxi trip data. This model standardizes column names
      and data types from the raw green_tripdata source, providing a clean foundation
      for downstream transformations.
    columns:
      - name: vendor_id
        description: Taxi technology provider (1 = Creative Mobile Technologies, 2 = VeriFone Inc.)
        data_tests:
          - not_null
      - name: rate_code_id
      - name: pickup_location_id
      - name: dropoff_location_id
      - name: pickup_datetime
        data_tests:
          - not_null
      - name: dropoff_datetime
      - name: store_and_fwd_flag
      - name: passenger_count
      - name: trip_distance
      - name: trip_type
      - name: fare_amount
      - name: extra
      - name: mta_tax
      - name: tip_amount
      - name: tolls_amount
      - name: ehail_fee
      - name: improvement_surcharge
      - name: total_amount
      - name: payment_type

  - name: stg_yellow_tripdata
    description: >
      Staging model for yellow taxi trip data. This model standardizes column names
      and data types from the raw yellow_tripdata source, providing a clean foundation
      for downstream transformations.
    columns:
      - name: vendor_id
        data_tests:
          - not_null
      - name: rate_code_id
      - name: pickup_location_id
      - name: dropoff_location_id
      - name: pickup_datetime
        data_tests:
          - not_null
      - name: dropoff_datetime
      - name: store_and_fwd_flag
      - name: passenger_count
      - name: trip_distance
      - name: fare_amount
      - name: extra
      - name: mta_tax
      - name: tip_amount
      - name: tolls_amount
      - name: improvement_surcharge
      - name: total_amount
      - name: payment_type

  - name: stg_fhv_tripdata
    description: >
      Staging model for FHV (For-Hire Vehicle) trip data.
      This model standardizes column names and filters invalid records
      from the raw fhv_tripdata source.
    columns:
      - name: dispatching_base_num
        description: TLC base license number of the dispatching base
        data_tests:
          - not_null

      - name: pickup_location_id
        description: TLC Taxi Zone where the trip started

      - name: dropoff_location_id
        description: TLC Taxi Zone where the trip ended

      - name: pickup_datetime
        description: Pickup date and time

      - name: dropoff_datetime
        description: Dropoff date and time

      - name: sr_flag
        description: Shared ride flag

      - name: affiliated_base_number
        description: TLC base license number of the affiliated base
